[project]
name = "leetcode"
version = "0.1.0"
description = "LeetCode solutions"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
dev-dependencies = [
    "mypy>=1.14.1",
    "ruff>=0.8.5",
]
